version: '3.1'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    entrypoint:
      - MYSQL_ROOT_PASSWORD=dan12
      - MYSQL_DATABASE=mydrive
      - MYSQL_USER=danil
      - MYSQL_PASSWORD=dan12
