version: '3.1'

services:
  
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: danil
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydrive


  stream:
    image: danilserenok/stream:latest
    container_name: stream
    ports:
      - "8881:8881"
