version: '3.8'

services:
  db:
    image: mysql:8.2
    ports:
      - "3306:3306"
    entrypoint:
      MYSQL_ROOT_PASSWORD: dan12
      MYSQL_DATABASE: mydrive
      MYSQL_USER: danil
      MYSQL_PASSWORD: dan12
